### ISSUE TITLE
Option to alias the field

### ISSUE THREAD

**Issue by mockthebear** [itzg/go-flagsfiller#17]
Could be a really useful addition to add a custom name for the field...
See this scenario:

```
type CurlFlags struct {
	DisableSSLCheck  bool `default:"false" usage:"Display body of responses" "alias": "k"`
       [...]
}
```
Upon calling the binary you can just use:
```
curl -k
```
instead of:
``` 
curl --disablesslcheck
```

**Comment by itzg** [comment]
I agree, that does seem useful. PRs are very welcome, if you want to contribute that.

As an implementation note, I did confirm that [the flag package](https://pkg.go.dev/flag@go1.19.4) does effectively support "short flags" like `-k`. As such, seems like aliases could be implemented as repeated flag declarations with a reference to the same field.

**Comment by itzg** [comment]
BTW, it should be accepting `DisableSSLCheck` as `--disable-ssl-check` but then maybe the field nees lowercase "ss" as `DisableSslCheck`.

**Comment by mockthebear** [comment]
I just created a pr :D

https://github.com/itzg/go-flagsfiller/pull/18

**Comment by ysmilda** [comment]
Would it be possible to create a release with these changes added?

**Comment by itzg** [comment]
Thanks for asking, I had apparently forgotten to do that with the PR. v1.9.2 now includes it.
